-- 코드를 입력하세요
SELECT DISTINCT USER_ID, PRODUCT_ID
FROM ONLINE_SALE O
WHERE (
    SELECT COUNT(*)
    FROM ONLINE_SALE S
    WHERE O.USER_ID = S.USER_ID AND O.PRODUCT_ID = S.PRODUCT_ID
) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC