# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO R1
# WHERE (FOOD_TYPE, FAVORITES) IN
# (
# SELECT FOOD_TYPE, MAX(FAVORITES)
# FROM REST_INFO R2
# GROUP BY FOOD_TYPE
# ) 
# ORDER BY FOOD_TYPE DESC

WITH RankedRestInfo AS (
    SELECT 
        FOOD_TYPE,
        REST_ID,
        REST_NAME,
        FAVORITES,
        ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) as rnk
    FROM REST_INFO
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM RankedRestInfo
WHERE rnk = 1
ORDER BY FOOD_TYPE DESC