SELECT T.YEAR YEAR, T.MONTH MONTH, T.GENDER GENDER, COUNT(*) AS USERS
FROM 
    (
    SELECT U.USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER
    FROM USER_INFO U
    JOIN ONLINE_SALE O
    ON U.USER_ID = O.USER_ID
    WHERE GENDER IS NOT NULL
    GROUP BY U.USER_ID, YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
    ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
    ) AS T
GROUP BY T.YEAR, T.MONTH, T.GENDER
