WITH RECURSIVE TMP AS (

    SELECT 0 AS TIME 
    
    UNION ALL
    
    SELECT TIME + 1
    FROM TMP
    WHERE TIME < 23

)

SELECT TIME AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS A
RIGHT OUTER JOIN TMP AS T
ON HOUR(A.DATETIME) = T.TIME
GROUP BY TIME
