WITH TMP AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)

SELECT B.WRITER_ID AS WRITER_ID, U.NICKNAME, B.TOTAL_SALES
FROM USED_GOODS_USER AS U
JOIN TMP AS B
ON U.USER_ID = B.WRITER_ID
ORDER BY B.TOTAL_SALES